/** Skills (spec/85 *Skills*, spec/20 *Skills and frontmatter edges*): the
 * `t1/skills.json` substrate, the generated `skilltree.md`, and the dependency
 * DAG checks. A skill is procedural memory — a distilled procedure plus the
 * tools it drives. The engine recognises, links, lists and points; it never
 * runs a tool: that is the agent's act under the agent's own sandbox. The twin
 * of the Python compile/skills.py, kept byte-identical in output. */
import { statSync } from "node:fs";
import { join } from "node:path";
import { posix } from "node:path";

import { cmpStr } from "../core/canonical";
import { posixDirname, posixJoin, posixNormpath, type Document } from "../core/bundle";

export { isSkill } from "../core/bundle";

export const SKILLTREE_FILE = "skilltree.md";
const SKILLTREE_PREAMBLE =
  "# Skill tree\n\n" +
  "_Generated by `brainpick compile` from `depends_on` frontmatter — edit the\n" +
  "skills, never this file._\n";

export interface SkillRecord {
  depends_on: string[];
  description: string | null;
  export: string[];
  path: string;
  title: string;
  tools: string[];
}

export interface SkillsArtifact {
  skills: SkillRecord[];
}

function isFile(path: string): boolean {
  try {
    return statSync(path).isFile();
  } catch {
    return false;
  }
}

/** A declared tool path -> bundle-relative when the file exists (rooted from
 * the bundle root first, then relative to the skill's directory); kept as
 * declared otherwise, so a missing tool stays visible as what was written. */
export function resolveTool(source: string, declared: string, root: string): string {
  const text = String(declared ?? "").trim();
  if (!text) return text;
  const base = text.replace(/^\/+/, "");
  if (isFile(join(root, base))) return base;
  if (!text.startsWith("/")) {
    const joined = posixNormpath(posixJoin(posixDirname(source), text));
    if (!joined.startsWith("..") && isFile(join(root, joined))) return joined;
  }
  return text;
}

/** The t1/skills.json payload: every skill sorted by path, with its RESOLVED
 * prerequisites (declared order) and its tool paths. */
export function buildSkills(docs: Document[], root: string): SkillsArtifact {
  const skills: SkillRecord[] = [];
  for (const doc of [...docs].sort((a, b) => cmpStr(a.path, b.path))) {
    if (!doc.skill) continue;
    skills.push({
      depends_on: [...doc.dependsOn],
      description: doc.description,
      export: [...doc.export],
      path: doc.path,
      title: doc.title,
      tools: doc.tools.map((t) => resolveTool(doc.path, t, root)),
    });
  }
  return { skills };
}

/** Every cycle in the depends_on DAG as a sorted path list, cycles sorted —
 * an authoring error reported as a compile warning, never a failure. */
export function dependencyCycles(skills: SkillsArtifact): string[][] {
  const edges = new Map<string, string[]>(skills.skills.map((s) => [s.path, [...s.depends_on]]));
  const index = new Map<string, number>();
  const low = new Map<string, number>();
  const onStack = new Set<string>();
  const stack: string[] = [];
  const cycles: string[][] = [];
  let counter = 0;

  const strongconnect = (node: string): void => {
    // Tarjan's SCCs
    index.set(node, counter);
    low.set(node, counter);
    counter += 1;
    stack.push(node);
    onStack.add(node);
    for (const nxt of edges.get(node) ?? []) {
      if (!edges.has(nxt)) continue;
      if (!index.has(nxt)) {
        strongconnect(nxt);
        low.set(node, Math.min(low.get(node)!, low.get(nxt)!));
      } else if (onStack.has(nxt)) {
        low.set(node, Math.min(low.get(node)!, index.get(nxt)!));
      }
    }
    if (low.get(node) === index.get(node)) {
      const component: string[] = [];
      for (;;) {
        const top = stack.pop()!;
        onStack.delete(top);
        component.push(top);
        if (top === node) break;
      }
      if (component.length > 1 || (edges.get(node) ?? []).includes(node)) {
        cycles.push(component.sort(cmpStr));
      }
    }
  };

  for (const path of [...edges.keys()].sort(cmpStr)) {
    if (!index.has(path)) strongconnect(path);
  }
  return cycles.sort((a, b) => cmpStr(a.join("\u0000"), b.join("\u0000")));
}

/** Where the generated tree lives: the directory of the first skill by path
 * (the template's skills/); null when the bundle holds no skill. */
export function skilltreePath(skills: SkillsArtifact): string | null {
  const first = skills.skills[0];
  if (!first) return null;
  return posixJoin(posixDirname(first.path), SKILLTREE_FILE).replace(/^\/+/, "");
}

function relativeTo(fromFile: string, target: string): string {
  return posix.relative(posixDirname(fromFile) || ".", target);
}

/** The whole skilltree.md (spec/20): one entry per skill sorted by path,
 * `needs` lines for resolved prerequisites, a `tools:` line when declared. */
export function renderSkilltree(skills: SkillsArtifact, treePath: string): string {
  const titles = new Map(skills.skills.map((s) => [s.path, s.title]));
  const lines = [SKILLTREE_PREAMBLE];
  for (const skill of skills.skills) {
    let entry = `- [${skill.title}](${relativeTo(treePath, skill.path)})`;
    if (skill.description) entry += ` — ${skill.description}`;
    lines.push(entry);
    for (const dep of skill.depends_on) {
      lines.push(`  - needs [${titles.get(dep) ?? dep}](${relativeTo(treePath, dep)})`);
    }
    if (skill.tools.length) {
      const joined = skill.tools.map((t) => `\`${relativeTo(treePath, t)}\``).join(", ");
      lines.push(`  - tools: ${joined}`);
    }
  }
  return lines.join("\n") + "\n";
}
