/** T1: the deterministic tier — graph, docs substrate, generated index (spec/20). */
import { cmpStr, sha256Hex } from "../core/canonical";
import { posixDirname, type Document } from "../core/bundle";

export const BEGIN_PREFIX = "<!-- brainpick:begin index (hash:";
export const END_MARKER = "<!-- brainpick:end index -->";
const PREAMBLE =
  "_Generated by `brainpick compile` from frontmatter descriptions — edit the\n" +
  "docs' `description` fields, not this block._";

export interface GraphNode {
  description: string | null;
  id: string;
  in: number;
  orphan: boolean;
  out: number;
  reserved: boolean;
  tags: string[];
  timestamp: string | null;
  title: string;
  type: string | null;
}

export interface GraphEdge {
  count: number;
  kind: string;
  label: string;
  source: string;
  target: string;
}

export interface GhostEdge {
  source: string;
  target: string;
}

export interface GraphStats {
  docs: number;
  edges: number;
  ghosts: number;
  islands: number;
  orphans: number;
  tags: number;
}

export interface Graph {
  edges: GraphEdge[];
  ghosts: GhostEdge[];
  islands: string[][];
  nodes: GraphNode[];
  stats: GraphStats;
  tags: Record<string, string[]>;
}

export interface DocRecord {
  description: string | null;
  path: string;
  reserved: boolean;
  sha256: string;
  tags: string[];
  text: string;
  timestamp: string | null;
  title: string;
  type: string | null;
}

export function buildGraph(docs: Document[]): Graph {
  const byPath = new Map(docs.map((d) => [d.path, d]));

  // collapse duplicate links: (source, target, kind) -> [count, first label]
  const collapsed = new Map<string, { source: string; target: string; kind: string; count: number; label: string }>();
  const ghostPairs = new Map<string, GhostEdge>();
  for (const doc of docs) {
    for (const link of doc.links) {
      const key = `${doc.path}\u0000${link.target}\u0000${link.kind}`;
      const existing = collapsed.get(key);
      if (existing) existing.count += 1;
      else collapsed.set(key, { source: doc.path, target: link.target, kind: link.kind, count: 1, label: link.text });
    }
    for (const ghost of doc.ghosts) {
      const key = `${doc.path}\u0000${ghost.target}`;
      if (!ghostPairs.has(key)) ghostPairs.set(key, { source: doc.path, target: ghost.target });
    }
  }

  const edges: GraphEdge[] = [...collapsed.values()].map((e) => ({
    count: e.count,
    kind: e.kind,
    label: e.label,
    source: e.source,
    target: e.target,
  }));
  edges.sort((a, b) => cmpStr(a.source, b.source) || cmpStr(a.target, b.target) || cmpStr(a.kind, b.kind));
  const ghosts = [...ghostPairs.values()].sort((a, b) => cmpStr(a.source, b.source) || cmpStr(a.target, b.target));

  const incoming = new Map<string, number>();
  const outgoing = new Map<string, number>();
  const nonreservedIn = new Map<string, Set<string>>();
  for (const e of edges) {
    outgoing.set(e.source, (outgoing.get(e.source) ?? 0) + 1);
    incoming.set(e.target, (incoming.get(e.target) ?? 0) + 1);
    if (!byPath.get(e.source)!.reserved) {
      let set = nonreservedIn.get(e.target);
      if (!set) nonreservedIn.set(e.target, (set = new Set()));
      set.add(e.source);
    }
  }

  const nodes: GraphNode[] = [...docs]
    .sort((a, b) => cmpStr(a.path, b.path))
    .map((doc) => ({
      description: doc.description,
      id: doc.path,
      in: incoming.get(doc.path) ?? 0,
      orphan: !doc.reserved && !(nonreservedIn.get(doc.path)?.size ?? 0),
      out: outgoing.get(doc.path) ?? 0,
      reserved: doc.reserved,
      tags: doc.tags,
      timestamp: doc.timestamp,
      title: doc.title,
      type: doc.type,
    }));

  const tagMap = new Map<string, string[]>();
  for (const doc of docs) {
    for (const tag of doc.tags) {
      let list = tagMap.get(tag);
      if (!list) tagMap.set(tag, (list = []));
      list.push(doc.path);
    }
  }
  const tags: Record<string, string[]> = {};
  for (const [tag, paths] of [...tagMap.entries()].sort((a, b) => cmpStr(a[0], b[0]))) {
    tags[tag] = [...paths].sort(cmpStr);
  }

  const islands = findIslands(docs, edges);

  const stats: GraphStats = {
    docs: nodes.length,
    edges: edges.length,
    ghosts: ghosts.length,
    islands: islands.length,
    orphans: nodes.filter((n) => n.orphan).length,
    tags: Object.keys(tags).length,
  };
  return { edges, ghosts, islands, nodes, stats, tags };
}

function findIslands(docs: Document[], edges: GraphEdge[]): string[][] {
  const nonreserved = new Set(docs.filter((d) => !d.reserved).map((d) => d.path));
  if (nonreserved.size === 0) return [];
  const adjacency = new Map<string, Set<string>>();
  for (const p of nonreserved) adjacency.set(p, new Set());
  for (const e of edges) {
    if (nonreserved.has(e.source) && nonreserved.has(e.target)) {
      adjacency.get(e.source)!.add(e.target);
      adjacency.get(e.target)!.add(e.source);
    }
  }

  const components: string[][] = [];
  const seen = new Set<string>();
  for (const start of [...nonreserved].sort(cmpStr)) {
    if (seen.has(start)) continue;
    const stack = [start];
    const component: string[] = [];
    seen.add(start);
    while (stack.length > 0) {
      const node = stack.pop()!;
      component.push(node);
      for (const neighbor of adjacency.get(node)!) {
        if (!seen.has(neighbor)) {
          seen.add(neighbor);
          stack.push(neighbor);
        }
      }
    }
    components.push(component.sort(cmpStr));
  }

  // sort by (size desc, first id): head = mainland, rest = islands, already in spec order
  components.sort((a, b) => b.length - a.length || cmpStr(a[0]!, b[0]!));
  return components.slice(1);
}

export function buildDocsRecords(docs: Document[]): DocRecord[] {
  return [...docs]
    .sort((a, b) => cmpStr(a.path, b.path))
    .map((doc) => ({
      description: doc.description,
      path: doc.path,
      reserved: doc.reserved,
      sha256: doc.sha256,
      tags: doc.tags,
      text: doc.body,
      timestamp: doc.timestamp,
      title: doc.title,
      type: doc.type,
    }));
}

export function renderIndexBlock(docs: Document[]): string {
  const groups = new Map<string, Document[]>();
  for (const doc of docs) {
    if (doc.reserved) continue;
    const dir = posixDirname(doc.path);
    let members = groups.get(dir);
    if (!members) groups.set(dir, (members = []));
    members.push(doc);
  }

  const ordered = [...groups.entries()].sort(
    (a, b) => Number(a[0] !== "") - Number(b[0] !== "") || cmpStr(a[0], b[0]),
  );
  const sections: string[] = [];
  for (const [directory, members] of ordered) {
    const heading = directory === "" ? "concepts" : directory;
    const entries: string[] = [];
    for (const doc of [...members].sort((a, b) => cmpStr(a.title, b.title) || cmpStr(a.path, b.path))) {
      let entry = `- [${doc.title}](${doc.path})`;
      if (doc.description) entry += ` — ${doc.description}`;
      entries.push(entry);
    }
    sections.push(`## ${heading}\n\n` + entries.join("\n"));
  }

  const body = PREAMBLE + "\n\n" + sections.join("\n\n") + "\n";
  const stamp = sha256Hex(body).slice(0, 8);
  return `${BEGIN_PREFIX}${stamp}) -->\n${body}${END_MARKER}`;
}

/** Insert or refresh the fenced block; hand-written content is never touched. */
export function applyIndexSection(existing: string | null, block: string): string {
  if (existing === null) {
    return '---\nokf_version: "0.1"\n---\n\n' + block + "\n";
  }

  const begin = existing.indexOf(BEGIN_PREFIX);
  if (begin !== -1) {
    let end = existing.indexOf(END_MARKER, begin);
    if (end !== -1) {
      end += END_MARKER.length;
      return existing.slice(0, begin) + block + existing.slice(end);
    }
  }
  return existing.replace(/\n+$/, "") + "\n\n" + block + "\n";
}
