"""Skills (spec/85 *Skills*, spec/20 *Skills and frontmatter edges*): the
`t1/skills.json` substrate, the generated `skilltree.md`, and the dependency
DAG checks. A skill is procedural memory — a distilled procedure plus the
tools it drives. The engine recognises, links, lists and points; it never runs
a tool: that is the agent's act under the agent's own sandbox."""
from __future__ import annotations

import posixpath
from pathlib import Path

from brainpick.core.bundle import Document, is_skill

__all__ = ["SKILLTREE_FILE", "build_skills", "dependency_cycles", "is_skill",
           "render_skilltree", "resolve_tool", "skilltree_path"]

SKILLTREE_FILE = "skilltree.md"
_SKILLTREE_PREAMBLE = (
    "# Skill tree\n\n"
    "_Generated by `brainpick compile` from `depends_on` frontmatter — edit the\n"
    "skills, never this file._\n"
)


def resolve_tool(source: str, declared: str, root: Path) -> str:
    """A declared tool path -> bundle-relative when the file exists (rooted from
    the bundle root first, then relative to the skill's directory); kept as
    declared otherwise, so a missing tool stays visible as what was written."""
    text = str(declared or "").strip()
    if not text:
        return text
    base = text.lstrip("/")
    if (root / base).is_file():
        return base
    if not text.startswith("/"):
        joined = posixpath.normpath(posixpath.join(posixpath.dirname(source), text))
        if not joined.startswith("..") and (root / joined).is_file():
            return joined
    return text


def build_skills(docs: list[Document], root: str | Path) -> dict:
    """The t1/skills.json payload: every skill sorted by path, with its RESOLVED
    prerequisites (declared order) and its tool paths."""
    root = Path(root)
    skills = []
    for doc in sorted(docs, key=lambda d: d.path):
        if not doc.skill:
            continue
        skills.append({
            "depends_on": list(doc.depends_on),
            "description": doc.description,
            "path": doc.path,
            "title": doc.title,
            "tools": [resolve_tool(doc.path, t, root) for t in doc.tools],
        })
    return {"skills": skills}


def dependency_cycles(skills: dict) -> list[list[str]]:
    """Every cycle in the depends_on DAG as a sorted path list, cycles sorted —
    an authoring error reported as a compile warning, never a failure."""
    edges = {s["path"]: list(s["depends_on"]) for s in skills["skills"]}
    index: dict[str, int] = {}
    low: dict[str, int] = {}
    on_stack: set[str] = set()
    stack: list[str] = []
    cycles: list[list[str]] = []
    counter = [0]

    def strongconnect(node: str) -> None:  # Tarjan's SCCs, iterative enough for a brain
        index[node] = low[node] = counter[0]
        counter[0] += 1
        stack.append(node)
        on_stack.add(node)
        for nxt in edges.get(node, []):
            if nxt not in edges:
                continue
            if nxt not in index:
                strongconnect(nxt)
                low[node] = min(low[node], low[nxt])
            elif nxt in on_stack:
                low[node] = min(low[node], index[nxt])
        if low[node] == index[node]:
            component = []
            while True:
                top = stack.pop()
                on_stack.discard(top)
                component.append(top)
                if top == node:
                    break
            if len(component) > 1 or node in edges.get(node, []):
                cycles.append(sorted(component))

    for path in sorted(edges):
        if path not in index:
            strongconnect(path)
    return sorted(cycles)


def skilltree_path(skills: dict) -> str | None:
    """Where the generated tree lives: the directory of the first skill by path
    (the template's skills/); None when the bundle holds no skill."""
    if not skills["skills"]:
        return None
    return posixpath.join(posixpath.dirname(skills["skills"][0]["path"]), SKILLTREE_FILE).lstrip("/")


def _relative(from_file: str, target: str) -> str:
    rel = posixpath.relpath(target, posixpath.dirname(from_file) or ".")
    return rel


def render_skilltree(skills: dict, tree_path: str) -> str:
    """The whole skilltree.md (spec/20): one entry per skill sorted by path,
    `needs` lines for resolved prerequisites, a `tools:` line when declared."""
    titles = {s["path"]: s["title"] for s in skills["skills"]}
    lines = [_SKILLTREE_PREAMBLE]
    for skill in skills["skills"]:
        entry = f"- [{skill['title']}]({_relative(tree_path, skill['path'])})"
        if skill["description"]:
            entry += f" — {skill['description']}"
        lines.append(entry)
        for dep in skill["depends_on"]:
            lines.append(f"  - needs [{titles.get(dep, dep)}]({_relative(tree_path, dep)})")
        if skill["tools"]:
            joined = ", ".join(f"`{_relative(tree_path, t)}`" for t in skill["tools"])
            lines.append(f"  - tools: {joined}")
    return "\n".join(lines) + "\n"
