"""T1: the deterministic tier — graph, docs substrate, generated index (spec/20)."""
from __future__ import annotations

import posixpath
from collections import defaultdict

from brainpick.core.bundle import Document
from brainpick.core.canonical import sha256_hex

BEGIN_PREFIX = "<!-- brainpick:begin index (hash:"
BEGIN_TEMPLATE = "<!-- brainpick:begin index (hash:{stamp}) -->"
END_MARKER = "<!-- brainpick:end index -->"
_PREAMBLE = (
    "_Generated by `brainpick compile` from frontmatter descriptions — edit the\n"
    "docs' `description` fields, not this block._"
)


def build_graph(docs: list[Document]) -> dict:
    by_path = {d.path: d for d in docs}

    # collapse duplicate links: (source, target, kind) -> [count, first label]
    collapsed: dict[tuple[str, str, str], list] = {}
    ghosts = []
    for doc in docs:
        for link in doc.links:
            key = (doc.path, link.target, link.kind)
            if key in collapsed:
                collapsed[key][0] += 1
            else:
                collapsed[key] = [1, link.text]
        for ghost in doc.ghosts:
            ghosts.append({"source": doc.path, "target": ghost.target})

    edges = [
        {"count": count, "kind": kind, "label": label, "source": source, "target": target}
        for (source, target, kind), (count, label) in collapsed.items()
    ]
    edges.sort(key=lambda e: (e["source"], e["target"], e["kind"]))
    ghosts = sorted({(g["source"], g["target"]) for g in ghosts})
    ghosts = [{"source": s, "target": t} for s, t in ghosts]

    incoming: dict[str, int] = defaultdict(int)
    outgoing: dict[str, int] = defaultdict(int)
    nonreserved_in: dict[str, set] = defaultdict(set)
    for e in edges:
        outgoing[e["source"]] += 1
        incoming[e["target"]] += 1
        if not by_path[e["source"]].reserved:
            nonreserved_in[e["target"]].add(e["source"])

    nodes = []
    for doc in sorted(docs, key=lambda d: d.path):
        nodes.append({
            "description": doc.description,
            "id": doc.path,
            "in": incoming[doc.path],
            "orphan": (not doc.reserved) and not nonreserved_in[doc.path],
            "out": outgoing[doc.path],
            "reserved": doc.reserved,
            "tags": doc.tags,
            "timestamp": doc.timestamp,
            "title": doc.title,
            "type": doc.type,
        })

    tags: dict[str, list[str]] = defaultdict(list)
    for doc in docs:
        for tag in doc.tags:
            tags[tag].append(doc.path)
    tags = {k: sorted(v) for k, v in sorted(tags.items())}

    islands = _islands(docs, edges)

    stats = {
        "docs": len(nodes),
        "edges": len(edges),
        "ghosts": len(ghosts),
        "islands": len(islands),
        "orphans": sum(1 for n in nodes if n["orphan"]),
        "tags": len(tags),
    }
    return {"edges": edges, "ghosts": ghosts, "islands": islands,
            "nodes": nodes, "stats": stats, "tags": tags}


def _islands(docs: list[Document], edges: list[dict]) -> list[list[str]]:
    nonreserved = {d.path for d in docs if not d.reserved}
    if not nonreserved:
        return []
    adjacency: dict[str, set] = {p: set() for p in nonreserved}
    for e in edges:
        if e["source"] in nonreserved and e["target"] in nonreserved:
            adjacency[e["source"]].add(e["target"])
            adjacency[e["target"]].add(e["source"])

    components: list[list[str]] = []
    seen: set[str] = set()
    for start in sorted(nonreserved):
        if start in seen:
            continue
        stack, component = [start], []
        seen.add(start)
        while stack:
            node = stack.pop()
            component.append(node)
            for neighbor in adjacency[node]:
                if neighbor not in seen:
                    seen.add(neighbor)
                    stack.append(neighbor)
        components.append(sorted(component))

    # sort by (size desc, first id): head = mainland, rest = islands, already in spec order
    components.sort(key=lambda c: (-len(c), c[0]))
    return components[1:]


def build_docs_records(docs: list[Document]) -> list[dict]:
    records = []
    for doc in sorted(docs, key=lambda d: d.path):
        records.append({
            "description": doc.description,
            "path": doc.path,
            "reserved": doc.reserved,
            "sha256": doc.sha256,
            "tags": doc.tags,
            "text": doc.body,
            "timestamp": doc.timestamp,
            "title": doc.title,
            "type": doc.type,
        })
    return records


def render_index_block(docs: list[Document]) -> str:
    groups: dict[str, list[Document]] = defaultdict(list)
    for doc in docs:
        if doc.reserved:
            continue
        groups[posixpath.dirname(doc.path)].append(doc)

    ordered = sorted(groups.items(), key=lambda item: (item[0] != "", item[0]))
    sections = []
    for directory, members in ordered:
        heading = "concepts" if directory == "" else directory
        entries = []
        for doc in sorted(members, key=lambda d: (d.title, d.path)):
            entry = f"- [{doc.title}]({doc.path})"
            if doc.description:
                entry += f" — {doc.description}"
            entries.append(entry)
        sections.append(f"## {heading}\n\n" + "\n".join(entries))

    body = _PREAMBLE + "\n\n" + "\n\n".join(sections) + "\n"
    stamp = sha256_hex(body.encode("utf-8"))[:8]
    return BEGIN_TEMPLATE.format(stamp=stamp) + "\n" + body + END_MARKER


def apply_index_section(existing: str | None, block: str) -> str:
    """Insert or refresh the fenced block; hand-written content is never touched."""
    if existing is None:
        return '---\nokf_version: "0.1"\n---\n\n' + block + "\n"

    begin = existing.find(BEGIN_PREFIX)
    if begin != -1:
        end = existing.find(END_MARKER, begin)
        if end != -1:
            end += len(END_MARKER)
            return existing[:begin] + block + existing[end:]
    return existing.rstrip("\n") + "\n\n" + block + "\n"
